services:
  app:
    image: tg_clone:1.0.0
    command: python3 /app/main.py
    restart: on-failure
    volumes:
      - ./config.ini:/app/config.ini:ro
    ports:
      - "8080:8080"

volumes:
  app_data: