services:
  app:
    image: tg_clone:1.0.0
    command: python3 /app/main.py
    restart: always
    volumes:
      - ./config.ini:/app/config.ini:ro
      - /root/.ssh/:/root/.ssh/:ro
    ports:
      - "8080:8080"
  tg_login:
    image: tg_clone:1.0.0
    working_dir: /app/crontabs
    command: python3 account/login.py
    restart: always
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./sessions:/app/sessions
  tg_dialog_info_sync:
    image: tg_clone:1.0.0
    working_dir: /app/crontabs
    command: python3 account/dialog_info_sync.py
    restart: always
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./sessions:/app/sessions
