services:
  app:
    image: tg_clone:1.0.0
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - SOURCE_GROUP_ID=${SOURCE_GROUP_ID}
      - DESTINATION_GROUP_ID=${DESTINATION_GROUP_ID}
    volumes:
      - .:/app